version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest' #the primary container, where your job's commands are run
    steps:
      - checkout #checkout the code in the project library
      - run: echo "hello world" #run the echo command
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/my-reports